# name = "John moriwal"
# print(name)
# print(type(name))
# print(name[5])

# for i in name:
#     print(i)

# for i in range(0, len(name)):
#     print(name[i])

name = "John Moriwal"
# print(name.capitalize())
# print(name.upper())
# print(name.lower())
# print(name.isupper())
# print(name.islower())
# print(name.isspace())
# print(name.isalnum())
# print(name.isalpha())
# print(name.isascii())
# print(name.isprintable())
# print(name.center(50))
# print(name.istitle())
# print(name.title())
# print(name.isdigit())
# print(name.isdecimal())
# print(name.find('J'))
# print(name.expandtabs(2))
# print(name.casefold())
# print(name.join('Hello'))
# print(name.split())
# print(name.rstrip('!'))
# print(name.lstrip('!'))
# print(name.strip('!'))
# print(name.startswith('J'))
# print(name.endswith('l'))
# print(name.isidentifier())
# txt1 = "My name is {fname}, I'm {age}".format(fname = "John", age = 36)
# print(txt1)
# print(name.replace('J', 'K'))
# dic = {'N': "John", "a": 20}
# s = str.maketrans(dic)
# print(s)
# print(name.removeprefix('J'))
# print(name.removesuffix('l'))
# print(name.rfind('o'))
# print(name.rjust(13, "k"))
# print(name.ljust(13, "k"))